apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: first-docker-replicaset
spec:
  replicas: 3 # Количество реплик
  selector:
    matchLabels:
      app: first-docker
  template:
    metadata:
      labels:
        app: first-docker
    spec:
      containers:
      - name: first-docker-container1
        image: gregtech5/first-docker:v1  
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: first-docker-service
spec:
  type: NodePort
  selector:
    app: first-docker
  ports:
    - port: 80
      nodePort: 31000
